from pathlib import Path


DEFAULT_CAMERA_NAME = "FaceTime HD Camera"

TEST_PHOTO_CAPTURE_INITIAL_SECONDS = 60
TEST_PHOTO_CAPTURE_INTERVAL_SECONDS = 60
LIVE_PHOTO_CAPTURE_INITIAL_SECONDS = 10 * 60
LIVE_PHOTO_CAPTURE_INTERVAL_SECONDS = 10 * 60

INTERVIEW_PHOTO_DIR = Path("/Users/flora/interview")
STATIC_INTERVIEW_PHOTO_PATH = INTERVIEW_PHOTO_DIR / "static.jpg"
TEST_INTERVIEW_PHOTO_PATH = INTERVIEW_PHOTO_DIR / "test.jpg"
LIVE_INTERVIEW_PHOTO_PATH = INTERVIEW_PHOTO_DIR / "live.jpg"
