AUDIO_SAMPLE_RATE = 16_000
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH_BYTES = 2
AUDIO_CHUNK_SECONDS = 0.1
AUDIO_PRE_ROLL_SECONDS = 0.3

STREAM_SEMANTIC_SILENCE_SECONDS = 2.5
STREAM_HARD_SILENCE_SECONDS = 7.5
DEFAULT_SILENCE_THRESHOLD = 500
