from pathlib import Path


AUDIO_SAMPLE_RATE = 16_000
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH_BYTES = 2
AUDIO_CHUNK_SECONDS = 0.1
AUDIO_PRE_ROLL_SECONDS = 0.3

DEFAULT_SILENCE_SECONDS = 5.0
DEFAULT_SILENCE_THRESHOLD = 500
DEFAULT_MAX_RECORD_SECONDS = 120.0

DEFAULT_TRANSCRIPTION_MODEL = "small"
DEFAULT_QUESTION_TRIGGER_MODE = "smart"

CHATGPT_URL = "https://chatgpt.com/"
DEFAULT_BROWSER_PROFILE = Path.home() / ".offergpt" / "browser-profile"
DEFAULT_CDP_URL = "http://127.0.0.1:9222"
PERSISTENT_TYPE_DELAY_MS = 25

DEFAULT_QUESTION_START_PHRASES = ("ok so the issue", "so the problem")
